#ifndef MANTIDUI_WIDGETS_CORE_DLLOPTION_H_
#define MANTIDUI_WIDGETS_CORE_DLLOPTION_H_

#include "MantidKernel/System.h"

#ifdef IN_MANTIDUI_WIDGETS_CORE
#define MANTIDUI_WIDGETS_CORE_PUBLIC DLLExport
#define MANTIDUI_WIDGETS_CORE_EXTERN
#else
#define MANTIDUI_WIDGETS_CORE_PUBLIC DLLImport
#define MANTIDUI_WIDGETS_CORE_EXTERN extern
#endif /* IN_MANTIDUI_WIDGETS_CORE */

#endif // MANTIDUI_WIDGETS_CORE_DLLOPTION_H_
